version: '3'

services:
  ws:
    restart: unless-stopped
    container_name: ws_checkers
    build:
      dockerfile: ./Dockerfile
    ports:
      - 88:88
    volumes:
      - ./checkers.db:/go/bin/checkers.db
    environment:
      DB_PATH: "/go/bin/checkers.db"
