version: '3'

services:
  ws:
    restart: unless-stopped
    container_name: ws_checkers
    build:
      dockerfile: ./Dockerfile
    ports:
      - 88:88
    volumes:
      - ./data:/go/bin/data
    environment:
      DB_PATH: "/go/bin/data/checkers.db"
    extra_hosts:
      - "host.docker.internal:host-gateway"
