name: Go Build, Test and Quality Gate
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.1'

      - name: Build
        run: go build -v ./...

      - name: Test and generate coverage
        run: CHECKERS_TESTING=1 go test -coverprofile=/dev/null ./... > go_test_output.txt

      - name: Show test results
        if: success() || failure()
        run: cat go_test_output.txt

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Check coverage
        run: python3 ./scripts/check_coverage.py < go_test_output.txt
